version: "3"
services:
  
  volume:
    image: tskehin/yetube_volume:1.0
    restart: "no"
    volumes:
      - yetube_videos:/yetube_videos
    # networks:
    #   - db_web_nw

  db:
    image: tskehin/yetube_db:1.0
    restart: always
    # networks:
    #   - db_web_nw

  web:
    image: tskehin/yetube_web:2.0
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "80:80"
    # networks:
    #   - db_web_nw
    volumes:
      - yetube_videos:/var/www/html/yetube_videos
    # links:
    #   - "db:yetube_db"

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    # networks:
    #   - db_web_nw

volumes:
  yetube_videos:

# networks:
#   db_web_nw:
#     driver: overlay



